#!/bin/bash

# Clear existing files
rm -r /lustre/*
mkdir -p /lustre/local/
mkdir -p /lustre/distributed

DISTRIBUTED="--distributed --dist_backend=sync-gRPC"
#DISTRIBUTED=

# Create ground truth files by copying existing files generated from local kernels, not the lustre kernels
cp /daphne/data/wine.dbdf /lustre/wine_original.dbdf.lustre
cp /daphne/data/wine.dbdf.meta /lustre/wine_original.dbdf.lustre.meta
cp /daphne/data/wine.dbdf /lustre/wine_original.dbdf
cp /daphne/data/wine.dbdf.meta /lustre/wine_original.dbdf.meta
cp /daphne/data/wine.csv /lustre/wine_original.csv
cp /daphne/data/wine.csv.meta /lustre/wine_original.csv.meta


./bin/daphne $DISTRIBUTED scripts/lustre_tests/lustre_kernels_write.daph A=\"/lustre/wine_original.dbdf.lustre\" B=\"/lustre/distributed/wine.dbdf.lustre\" C=\"/lustre/distributed/wine.csv.lustre\"
./bin/daphne $DISTRIBUTED scripts/lustre_tests/lustre_kernels_read.daph A=\"/lustre/distributed/wine.dbdf.lustre\" B=\"/lustre/distributed/wine_compare.dbdf.lustre\" C=\"/lustre/distributed/wine.csv.lustre\" D=\"/lustre/distributed/wine_compare.csv.lustre\"

# Test that distributed and local runtime generate the same files
# Local runtime can read from the original file, not the .lustre

./bin/daphne scripts/lustre_tests/lustre_kernels_write.daph A=\"/lustre/wine_original.dbdf\" B=\"/lustre/local/wine.dbdf.lustre\" C=\"/lustre/local/wine.csv.lustre\"
./bin/daphne scripts/lustre_tests/lustre_kernels_read.daph A=\"/lustre/local/wine.dbdf.lustre\" B=\"/lustre/local/wine_compare.dbdf.lustre\" C=\"/lustre/local/wine.csv.lustre\" D=\"/lustre/local/wine_compare.csv.lustre\"

# Compare local and distributed runtime outputs
diff -qrs /lustre/local /lustre/distributed
if [ $? -ne 0 ]; then
    echo "FAIL: Local and Distributed runtime comparison";
else
    echo "PASS: Local and Distributed runtime comparison";
fi

diff /daphne/data/wine.dbdf /lustre/distributed/wine.dbdf.lustre
if [ $? -ne 0 ]; then
    echo "FAIL: Lustre generated dbdf files";
else
    echo "PASS: Lustre generated dbdf files";
fi

diff /lustre/distributed/wine_compare.dbdf.lustre /lustre/distributed/wine.dbdf.lustre
if [ $? -ne 0 ]; then
    echo "FAIL: Lustre generated dbdf files";
else
    echo "PASS: Lustre generated dbdf files";
fi

diff /lustre/distributed/wine_compare.csv.lustre /lustre/distributed/wine.csv.lustre
if [ $? -ne 0 ]; then
    echo "FAIL: Lustre generated csv files";
else
    echo "PASS: Lustre generated csv files";
fi

# Test that the actual data read are correct by comparing the matrix generated by existing kernels and the lustre kernels
# Do this for both distributed and local runtimes
# This has to be done in daphne level

./bin/daphne scripts/lustre_tests/lustre_kernels_compare.daph A=\"/lustre/wine_original.dbdf\" B=\"/lustre/distributed/wine.dbdf.lustre\"
./bin/daphne scripts/lustre_tests/lustre_kernels_compare.daph A=\"/lustre/wine_original.csv\" B=\"/lustre/distributed/wine.csv.lustre\"

./bin/daphne scripts/lustre_tests/lustre_kernels_compare.daph A=\"/lustre/wine_original.dbdf\" B=\"/lustre/local/wine.dbdf.lustre\"
./bin/daphne scripts/lustre_tests/lustre_kernels_compare.daph A=\"/lustre/wine_original.csv\" B=\"/lustre/local/wine.csv.lustre\"
